### ISSUE TITLE
configurators.forEach

### ISSUE THREAD

**Issue by artomka** [skuethe/MMM-Spotify#141]
Hi. When I try to get authorization with “node first_auth.js“ all the time I have this error: 

```
pi@raspberrypi:~/MagicMirror/modules/MMM-Spotify $ node first_auth.js
/home/pi/MagicMirror/modules/MMM-Spotify/first_auth.js:10
    configurators.forEach(configurator => {
                  ^

TypeError: configurators.forEach is not a function
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Spotify/first_auth.js:10:19)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```
How can I solve this, please?

**Comment by skuethe** [comment]
As you closed the issue directly I assume it is now working?
If not: did you execute all steps before hand (especially the install in step 1)?
