### ISSUE TITLE
node first_auth not working correctly

### ISSUE THREAD

**Issue by mrjdar** [skuethe/MMM-Spotify#168]
I'm still somewhat new to these, but this is my 3rd basic MM build and for some reason I'm having issues with getting this module up and running this time around.
I have it running just fine on another setup, as well I have the MMM-NowPlayingOnSpotify module up and running just fine, though I seem to be running into the issue at the Get Auth stage.

I initially thought it may have been the Client ID being used in 2 other MM modules. So I started fresh with installing the module and creating a new app within the Spotify Dev Dashboard. Everything goes smoothly until I go to the Get Auth stage. When I run that per the instructions I get the error:

```
/MagicMirror/modules/MMM-Spotify $ node first_auth.js
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'request'
Require stack:
- /home/pi/MagicMirror/modules/MMM-Spotify/Spotify.js
- /home/pi/MagicMirror/modules/MMM-Spotify/first_auth.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Spotify/Spotify.js:9:17)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/pi/MagicMirror/modules/MMM-Spotify/Spotify.js',
    '/home/pi/MagicMirror/modules/MMM-Spotify/first_auth.js'
  ]
}
```

**Comment by skuethe** [comment]
Interesting. Can you try installing the missing module manually:

```bash
npm install request
```

**Comment by mrjdar** [comment]
That did the trick! Thank you for the quick response on this! @skuethe

**Comment by skuethe** [comment]
I am re-opening this issue, as this needs some code adjustments, so other people don't run into this issue in the future :)
Will then close it with a PR.
