### ISSUE TITLE
"TypeError: configurators.forEach is not a function" when creating a token

### ISSUE THREAD

**Issue by ivanovd** [skuethe/MMM-Spotify#188]
I am getting the following when trying to create a token:

```
node first_auth.js
/home/pi/MagicMirror/modules/MMM-Spotify/first_auth.js:10
  configurators.forEach((configurator) => {
                ^

TypeError: configurators.forEach is not a function
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Spotify/first_auth.js:10:17)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47
```

```
pi@raspberrypi:~/MagicMirror/modules/MMM-Spotify $ node -v
v14.19.1
pi@raspberrypi:~/MagicMirror/modules/MMM-Spotify $ npm -v
6.14.16
```

```
┌──────────┬────┬─────────┬──────┬─────┬─────────┬─────────┬────────┬─────┬────────┬──────┬──────────┐
│ App name │ id │ version │ mode │ pid │ status  │ restart │ uptime │ cpu │ mem    │ user │ watching │
├──────────┼────┼─────────┼──────┼─────┼─────────┼─────────┼────────┼─────┼────────┼──────┼──────────┤
│ mm       │ 0  │ 2.19.0  │ fork │ 0   │ stopped │ 12      │ 0      │ 0%  │ 0 B    │ pi   │ disabled │
└──────────┴────┴─────────┴──────┴─────┴─────────┴─────────┴────────┴─────┴────────┴──────┴──────────┘
```

**Comment by skuethe** [comment]
Please validate your `spotify.config.json` input. Make sure that your content is wrapped inside an array (f.e. when running a single account:
```json
[
  {
    "..."
  }
]
```

Also double check that all necessary modules are installed by running `npm install`.
I am running the same node and npm versions and can not reproduce this out of the box.

**Comment by skuethe** [comment]
Okay, I could successfully reproduce this when not having the json code inside an array:
```json
  {
    "..."
  }
```
instead of:
```json
[
  {
    "..."
  }
]
```

**Comment by ivanovd** [comment]
@skuethe it worked. Thanks. I guess that since I reverted back to an old backup, the config was an old version thus the issue. Thanks once again.

**Comment by skuethe** [comment]
great to hear that it worked!
