### ISSUE TITLE
Error while try to 'Get Auth'

### ISSUE THREAD

**Issue by M1dn8** [skuethe/MMM-Spotify#27]
Hey,

I tried to install your awesome module but get an error on part 4 'Get Auth'.

After i send 'node first_auth.js' this message came back

node first_auth.js
/home/pi/MagicMirror/modules/MMM-Spotify/node_modules/open/index.js:16
const wslToWindowsPath = async path => {
                               ^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Spotify/Spotify.js:11:13)

i tried also to install 'open' but still same problem :(

could anyone help me pls?!

Thank u for your work!!!

**Comment by eouia** [comment]
I think your node version seems too low to handle this module. How's your node version?

**Comment by M1dn8** [comment]
Thank you for your answer!
I could and will check it today evening and will try to update node as well...hope it will help ;)

see u later

**Comment by M1dn8** [comment]
node -v
v6.17.1
after update node
node -v = v10.16.3
nodejs -v = v6.17.1

after updating node to v10.16.3 the module works :)

thank you very much!!!
