### ISSUE TITLE
Crash when lost internet connexion

### ISSUE THREAD

**Issue by bugsounet** [skuethe/MMM-Spotify#30]
** to inspect: 

TypeError: Cannot read property 'statusCode' of undefined
at Request.request [as _callback] (/home/pi/MagicMirror/modules/MMM-Spotify/Spotify.js:189:23)
at self.callback (/home/pi/MagicMirror/node_modules/request/request.js:185:22)
at Request.emit (events.js:182:13)
at Request.onRequestError (/home/pi/MagicMirror/node_modules/request/request.js:881:8)
at ClientRequest.emit (events.js:182:13)
at TLSSocket.socketErrorListener (_http_client.js:382:9)
at TLSSocket.emit (events.js:182:13)
at emitErrorNT (internal/streams/destroy.js:82:8)
at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
at process._tickCallback (internal/process/next_tick.js:63:19)

-> crash MMM-Spotify and need to restart MM

**Comment by eouia** [comment]
But, if your MM lost internet connection, you should restart the whole system anyway. (for calendar or other modules)
However, I'll inspect it. thank you for the reporting.
