### ISSUE TITLE
Error: listen EADDRINUSE: address already in use :::8888

### ISSUE THREAD

**Issue by nikobix** [skuethe/MMM-Spotify#32]
Hi, bit of a newby here. Trying to install Spotfy MM. 
Got as far as running the first_auth.js and get the below error. 
Any ideas, or have I done something wrong.
I have api key info from Spotify and set the Redirect address to http://localhost:8888/callback

pi@raspberrypi:~/MagicMirror/modules/MMM-Spotify $ node first_auth.js           [SPOTIFY_AUTH] Opening URL.(https://accounts.spotify.com/authorize?response_type=code&client_id="API KEY"&scope=user-read-private%20app-remote-control%20playlist-read-private%20streaming%20user-read-playback-state%20user-modify-playback-state&redirect_uri=http%3A%2F%2Flocalhost%3A8888%2Fcallback&state=1578324664790&show_dialog=true)
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::8888
    at Server.setupListenHandle [as _listen2] (net.js:1280:14)
    at listenInCluster (net.js:1328:12)
    at Server.listen (net.js:1415:7)
    at Function.listen (/home/pi/MagicMirror/node_modules/express/lib/application.js:618:24)
    at Spotify.authflow (/home/pi/MagicMirror/modules/MMM-Spotify/Spotify.js:96:8)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Spotify/first_auth.js:13:6)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
Emitted 'error' event at:
    at emitErrorNT (net.js:1307:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

**Comment by eouia** [comment]
Your 8888 port might be being used already.  Try another port.

**Comment by nikobix** [comment]
Thanks eouia, 

I figured it out. I was running the pi via a remote terminal. Of course I did not see the pop up to log into Spotify.
Ran this directly on the PI after a reboot and it accepted the port and gave me the pop up. 
All working now, great. 
Thanks for a great app.

**Comment by eouia** [comment]
nice to hear it.
