### ISSUE TITLE
Error to search

### ISSUE THREAD

**Issue by arlindonatal** [skuethe/MMM-Spotify#62]
I'm using MMM-AssistantMk2 to send voice command. But, when i call the command search i have this error:

```
[2020-05-12 16:59:08.833] [LOG]    [AMK2] RECIPE_LOADED: with-MMM-Spotify.js
[2020-05-12 16:59:08.837] [LOG]    [AMK2] AssistantMk2 is initialized.
[2020-05-12 16:59:09.164] [LOG]    [VOLUME] Set Volume To: 100
[2020-05-12 16:59:11.220] [LOG]    [MMM-Spotify] Starting
[2020-05-12 16:59:37.933] [LOG]    Whoops! There was an uncaught exception...
[2020-05-12 16:59:37.942] [ERROR]  TypeError: Cannot read property 'search' of null
    at Class.searchAndPlay (/home/pi/MagicMirror/modules/MMM-Spotify/node_helper.js:215:22)
    at Class.socketNotificationReceived (/home/pi/MagicMirror/modules/MMM-Spotify/node_helper.js:188:18)
    at Socket.<anonymous> (/home/pi/MagicMirror/js/node_helper.js:113:11)
    at Socket.emit (events.js:200:13)
    at /home/pi/MagicMirror/node_modules/socket.io/lib/socket.js:528:12
    at processTicksAndRejections (internal/process/task_queues.js:82:9)

```
My configurations:

```
  transcriptionHooks: {
    "SEARCH_SPOTIFY": {
      pattern: "tocar (.*) no spotify",
      command: "SEARCH_SPOTIFY"
    },

  commands: {
    "SEARCH_SPOTIFY": {
      notificationExec: {
        notification: "SPOTIFY_SEARCH",
        payload: (params) => {
	  console.log("SPOTIFY_SEARCH @",params)
          return {
            type: "artist,track,album,playlist",
            query: params[1], 
            random:false,
          }
        }
      },
      soundExec: {
        chime: "open"
      }
    },
```

**Comment by bugsounet** [comment]
thanks for this report
we are working around new version of this module
so we will inspect search function

I will be back to you as soon as possible :)

**Comment by bugsounet** [comment]
Can I have your request to have this error ?
because i have no error on Spotify search

**Comment by arlindonatal** [comment]
> Can I have your request to have this error ?
> because i have no error on Spotify search

I updated now and its works.

Thnks!
